#define DNA_MUTANT_COLOR_PRIMARY_BLOCK 17
#define DNA_MUTANT_COLOR_SECONDARY_BLOCK 18
#define DNA_MUTANT_COLOR_TERTIARY_BLOCK 19
#define DNA_SKIN_COLOR_BLOCK 20
//#define DNA_EARS_BLOCK
#define DNA_EARS_COLOR_PRIMARY_BLOCK 21
#define DNA_EARS_COLOR_SECONDARY_BLOCK 22
#define DNA_EARS_COLOR_TERTIARY_BLOCK 23
//#define DNA_TAIL_BLOCK
#define DNA_TAIL_COLOR_PRIMARY_BLOCK 24
#define DNA_TAIL_COLOR_SECONDARY_BLOCK 25
#define DNA_TAIL_COLOR_TERTIARY_BLOCK 26
//#define DNA_SNOUT_BLOCK
#define DNA_SNOUT_COLOR_PRIMARY_BLOCK 27
#define DNA_SNOUT_COLOR_SECONDARY_BLOCK 28
#define DNA_SNOUT_COLOR_TERTIARY_BLOCK 29
//#define DNA_HORNS_BLOCK
#define DNA_HORNS_COLOR_PRIMARY_BLOCK 30
#define DNA_HORNS_COLOR_SECONDARY_BLOCK 31
#define DNA_HORNS_COLOR_TERTIARY_BLOCK 32
//#define DNA_FRILLS_BLOCK
#define DNA_FRILLS_COLOR_PRIMARY_BLOCK 33
#define DNA_FRILLS_COLOR_SECONDARY_BLOCK 34
#define DNA_FRILLS_COLOR_TERTIARY_BLOCK 35
//#define DNA_SPINES_BLOCK
#define DNA_SPINES_COLOR_PRIMARY_BLOCK 36
#define DNA_SPINES_COLOR_SECONDARY_BLOCK 37
#define DNA_SPINES_COLOR_TERTIARY_BLOCK 38
//#define DNA_MOTH_WINGS_BLOCK
#define DNA_MOTH_WINGS_COLOR_PRIMARY_BLOCK 39
#define DNA_MOTH_WINGS_COLOR_SECONDARY_BLOCK 40
#define DNA_MOTH_WINGS_COLOR_TERTIARY_BLOCK 41
//#define DNA_MOTH_ANTENNAE_BLOCK
#define DNA_MOTH_ANTENNAE_COLOR_PRIMARY_BLOCK 42
#define DNA_MOTH_ANTENNAE_COLOR_SECONDARY_BLOCK 43
#define DNA_MOTH_ANTENNAE_COLOR_TERTIARY_BLOCK 44

/// This number needs to equal the total number of DNA feature blocks
#define DNA_FEATURE_BLOCKS 44
